update gradle / update mindustry

diff --git a/run-deploy b/run-deploy
--- a/run-deploy
+++ b/run-deploy
@@ -1,11 +1,39 @@
 #!/usr/bin/bash
 
-./update-sprites
+#!/usr/bin/bash
 
-if [[ ! $? == '0' ]]; then
-    echo "Sprites update failed"
-    exit 1
-fi
+[[ ! -d "../Mindustry" ]] && echo "Mindustry source code not found" && exit 1
+[[ ! -d "../Mindustry/core/assets-raw/sprites_out" ]] && echo "Sprites not found" && exit 1
+[[ ! -d "../Mindustry/core/assets/sprites" ]] && echo "Sprites not found" && exit 1
+
+[[ -d "./assets" ]] && rm -rf "./assets"
+
+echo "Copying sprites"
+
+mkdir "./assets"
+cp "../Mindustry/core/assets/sprites/error.png" "./assets"
+cp "../Mindustry/core/assets/sprites/sprites.aatls" "./assets"
+cp "../Mindustry/core/assets/sprites/schematic-background.png" "./assets"
+
+cp -r "../Mindustry/core/assets-raw/sprites_out" "./assets"
+mv "./assets/sprites_out" "./assets/sprites"
+
+cut -c 1-64 <<< `find "../Mindustry/core/assets-raw/sprites_out" -type f | xargs -L 1 sha256sum` | sort | sha256sum | cut -c 1-64 > sprites-hash
+
+rm gradle.properties
+
+lastDir=`pwd`
+cd "../Mindustry"
+
+mindHash=`git rev-parse HEAD`
+arcHash=`tail -n1 gradle.properties | cut -c 9-`
+
+cd "${lastDir}"
+
+echo "mindustryHash=${mindHash}" >> gradle.properties
+echo "arcHash=${arcHash}" >> gradle.properties
+
+echo "Updated hashes"
 
 ./gradlew dist --no-daemon -q
 
@@ -15,6 +43,8 @@ if [[ ! $? == '0' ]]; then
 fi
 
 cp  ./build/libs/previewer.jar ../Botzilla/schematic-previewer.jar
+
+[[ $# -ne 0 ]] && exit 1
 
 scp ./build/libs/previewer.jar nydus6:/tmp/schematic-previewer.jar
 ssh nydus6 cp /tmp/schematic-previewer.jar /opt/botzilla/schematic-previewer.jar
